spring.application.name=BT8
pring.profiles.active=sqlserver


spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=crudBT8;encrypt=false
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true